server:
  port: 9099

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.149:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: emp-service

logging:
  level:
    org.exampledriven.eureka.customer.shared.CustomerServiceFeignClient: info
    org.exampledriven.eureka: INFO